INSERT INTO episode_movie (
    id_series_film,
    no_episode,
    judul,
    tanggal_keluar,
    tanggal_ditambahkan,
    durasi,
    path_gambar_hero,
    path_gambar_portrait,
    path_gambar_landscape,
    path_gambar_thumbnail,
    ringkasan
)
VALUES
(
    1,
    1,
    "My",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    1,
    2,
    "Hero",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    1,
    3,
    "Academia",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    1,
    4,
    "My Hero",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    1,
    5,
    "Hero Academia",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    2,
    1,
    "Alice",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    2,
    2,
    "In",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    2,
    3,
    "Borderland",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    2,
    4,
    "Alice in",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    2,
    5,
    "In Borderland",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    1,
    "All",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    2,
    "Of",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    3,
    "Us",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    3,
    4,
    "Are",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    5,
    "Dead",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    6,
    "All of",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    7,
    "Of Us",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    8,
    "Us Are",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    3,
    9,
    "Are Dead",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    3,
    10,
    "Dead All",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    5,
    1,
    "Bat",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    5,
    2,
    "Man",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    8,
    1,
    "Blue",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    8,
    2,
    "Lock",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    8,
    3,
    "Blue Lock",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    8,
    4,
    "Lock Blue",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    8,
    5,
    "Blue Blue",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    11,
    1,
    "Duty",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    11,
    2,
    "After",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    11,
    3,
    "School",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    11,
    4,
    "Duty after",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    11,
    5,
    "After School",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    24,
    1,
    "Spi",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    25,
    1,
    "The",
    "2023-01-01",
    "2023-01-01",
    31,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-1.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    25,
    2,
    "Little",
    "2023-01-01",
    "2023-01-01",
    32,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-2.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    25,
    3,
    "Stuart",
    "2023-01-01",
    "2023-01-01",
    33,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-3.svg",
    "[long] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis. 
    Curae cursus turpis fames at dictum tempor nostra placerat ridiculus, maecenas neque quam egestas aliquet luctus a suspendisse, curabitur lacus platea habitant tristique faucibus augue torquent. 
    Quam lobortis laoreet dui massa ad montes primis ac, eget eleifend hac nulla turpis ridiculus risus in magnis, sagittis morbi nisi potenti sodales convallis torquent."
),
(
    25,
    4,
    "The Little",
    "2023-01-01",
    "2023-01-01",
    34,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-4.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
),
(
    25,
    5,
    "Little Stuart",
    "2023-01-01",
    "2023-01-01",
    35,
    "",
    "",
    "",
    "/images/poster-thumbnail/ted-5.svg",
    "[short] Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas donec vivamus aptent proin, erat odio risus mi leo penatibus sed aliquet nibh dis."
);